/**
 * Initial dataset of 18 realistic fleet vehicles distributed across Indian logistics corridors.
 */

export const INITIAL_VEHICLES = [
  {
    vehicleId: 'TRUCK-001',
    registrationNumber: 'DL-01-AB-1029',
    driverName: 'Rajesh Kumar',
    vehicleType: 'Heavy Truck',
    location: {
      city: 'Delhi',
      state: 'Delhi',
      lat: 28.6139,
      lng: 77.2090,
      heading: 45,
      address: 'NH-48, Mahipalpur Logistics Hub',
    },
    status: 'OK',
    currentSpeed: 68,
    fuelLevel: 82,
    engineTemperature: 83,
    batteryLevel: 94,
    totalDistance: 45280,
  },
  {
    vehicleId: 'TRUCK-002',
    registrationNumber: 'MH-04-CD-3482',
    driverName: 'Amit Shinde',
    vehicleType: 'Heavy Truck',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      lat: 19.0760,
      lng: 72.8777,
      heading: 180,
      address: 'Eastern Express Highway, Chembur',
    },
    status: 'OK',
    currentSpeed: 55,
    fuelLevel: 64,
    engineTemperature: 86,
    batteryLevel: 90,
    totalDistance: 78920,
  },
  {
    vehicleId: 'TRUCK-003',
    registrationNumber: 'KA-05-EF-9921',
    driverName: 'Suresh Gowda',
    vehicleType: 'Heavy Truck',
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      lat: 12.9716,
      lng: 77.5946,
      heading: 120,
      address: 'Hosur Road, Electronic City Toll',
    },
    status: 'WARN',
    currentSpeed: 72,
    fuelLevel: 22, // Below 25% warning
    engineTemperature: 92, // Above 90°C warning
    batteryLevel: 85,
    totalDistance: 31200,
  },
  {
    vehicleId: 'TRUCK-004',
    registrationNumber: 'TS-09-GH-4819',
    driverName: 'Venkat Rao',
    vehicleType: 'Heavy Truck',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      lat: 17.3850,
      lng: 78.4867,
      heading: 90,
      address: 'Outer Ring Road, Gachibowli Junction',
    },
    status: 'OK',
    currentSpeed: 80,
    fuelLevel: 75,
    engineTemperature: 84,
    batteryLevel: 92,
    totalDistance: 62410,
  },
  {
    vehicleId: 'TRUCK-005',
    registrationNumber: 'MH-12-JK-6723',
    driverName: 'Nitin Deshmukh',
    vehicleType: 'Heavy Truck',
    location: {
      city: 'Pune',
      state: 'Maharashtra',
      lat: 18.5204,
      lng: 73.8567,
      heading: 270,
      address: 'Mumbai-Pune Expressway, Talegaon',
    },
    status: 'OK',
    currentSpeed: 62,
    fuelLevel: 58,
    engineTemperature: 81,
    batteryLevel: 88,
    totalDistance: 53100,
  },
  {
    vehicleId: 'TRUCK-006',
    registrationNumber: 'TN-07-LM-5501',
    driverName: 'Murugan Pillai',
    vehicleType: 'Heavy Truck',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      lat: 13.0827,
      lng: 80.2707,
      heading: 330,
      address: 'Grand Southern Trunk Rd, Guindy',
    },
    status: 'CRITICAL',
    currentSpeed: 88,
    fuelLevel: 8, // Below 10% critical
    engineTemperature: 103, // Above 100°C critical
    batteryLevel: 78,
    totalDistance: 94150,
  },
  {
    vehicleId: 'VAN-001',
    registrationNumber: 'DL-04-NP-2211',
    driverName: 'Vikas Sharma',
    vehicleType: 'Delivery Van',
    location: {
      city: 'Delhi',
      state: 'Delhi',
      lat: 28.7041,
      lng: 77.1025,
      heading: 15,
      address: 'Ring Road, Rohini Sector 10',
    },
    status: 'OK',
    currentSpeed: 42,
    fuelLevel: 90,
    engineTemperature: 76,
    batteryLevel: 95,
    totalDistance: 18400,
  },
  {
    vehicleId: 'VAN-002',
    registrationNumber: 'MH-01-QR-8832',
    driverName: 'Prashant Patil',
    vehicleType: 'Delivery Van',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      lat: 19.2183,
      lng: 72.9781,
      heading: 200,
      address: 'Ghodbunder Road, Thane West',
    },
    status: 'OK',
    currentSpeed: 48,
    fuelLevel: 70,
    engineTemperature: 78,
    batteryLevel: 91,
    totalDistance: 29500,
  },
  {
    vehicleId: 'VAN-003',
    registrationNumber: 'KA-01-ST-3390',
    driverName: 'Kiran Reddy',
    vehicleType: 'Delivery Van',
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      lat: 12.9279,
      lng: 77.6271,
      heading: 45,
      address: 'Koramangala 80ft Road, 4th Block',
    },
    status: 'OK',
    currentSpeed: 38,
    fuelLevel: 85,
    engineTemperature: 75,
    batteryLevel: 96,
    totalDistance: 14200,
  },
  {
    vehicleId: 'VAN-004',
    registrationNumber: 'GJ-01-UV-7744',
    driverName: 'Jignesh Patel',
    vehicleType: 'Delivery Van',
    location: {
      city: 'Ahmedabad',
      state: 'Gujarat',
      lat: 23.0225,
      lng: 72.5714,
      heading: 60,
      address: 'Sarkhej - Gandhinagar Highway',
    },
    status: 'WARN',
    currentSpeed: 64,
    fuelLevel: 19, // Below 25% warning
    engineTemperature: 88,
    batteryLevel: 80,
    totalDistance: 38700,
  },
  {
    vehicleId: 'VAN-005',
    registrationNumber: 'RJ-14-WX-1234',
    driverName: 'Manish Meena',
    vehicleType: 'Delivery Van',
    location: {
      city: 'Jaipur',
      state: 'Rajasthan',
      lat: 26.9124,
      lng: 75.7873,
      heading: 135,
      address: 'Tonk Road, Durgapura Flyover',
    },
    status: 'OK',
    currentSpeed: 50,
    fuelLevel: 78,
    engineTemperature: 79,
    batteryLevel: 93,
    totalDistance: 21900,
  },
  {
    vehicleId: 'VAN-006',
    registrationNumber: 'WB-02-YZ-9876',
    driverName: 'Subhash Bose',
    vehicleType: 'Delivery Van',
    location: {
      city: 'Kolkata',
      state: 'West Bengal',
      lat: 22.5726,
      lng: 88.3639,
      heading: 225,
      address: 'EM Bypass, Salt Lake Stadium',
    },
    status: 'OK',
    currentSpeed: 44,
    fuelLevel: 62,
    engineTemperature: 77,
    batteryLevel: 89,
    totalDistance: 33400,
  },
  {
    vehicleId: 'EV-001',
    registrationNumber: 'DL-03-EV-0001',
    driverName: 'Anil Tyagi',
    vehicleType: 'Cargo EV',
    location: {
      city: 'Delhi',
      state: 'Delhi',
      lat: 28.5355,
      lng: 77.3910,
      heading: 90,
      address: 'Noida Expressway, Sector 128',
    },
    status: 'OK',
    currentSpeed: 52,
    fuelLevel: 100, // EV full virtual charge
    engineTemperature: 68,
    batteryLevel: 88,
    totalDistance: 11200,
  },
  {
    vehicleId: 'EV-002',
    registrationNumber: 'KA-03-EV-0042',
    driverName: 'Girish Naidu',
    vehicleType: 'Cargo EV',
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      lat: 12.9856,
      lng: 77.7376,
      heading: 180,
      address: 'ITPL Main Road, Whitefield',
    },
    status: 'WARN',
    currentSpeed: 45,
    fuelLevel: 100,
    engineTemperature: 72,
    batteryLevel: 28, // Below 30% battery warning
    totalDistance: 16800,
  },
  {
    vehicleId: 'EV-003',
    registrationNumber: 'MH-03-EV-0108',
    driverName: 'Sunil Jadhav',
    vehicleType: 'Cargo EV',
    location: {
      city: 'Pune',
      state: 'Maharashtra',
      lat: 18.5913,
      lng: 73.7389,
      heading: 315,
      address: 'Hinjawadi Phase 1, IT Park Hub',
    },
    status: 'CRITICAL',
    currentSpeed: 58,
    fuelLevel: 100,
    engineTemperature: 85,
    batteryLevel: 12, // Below 15% battery critical
    totalDistance: 24100,
  },
  {
    vehicleId: 'BUS-001',
    registrationNumber: 'DL-01-EX-5566',
    driverName: 'Harinder Singh',
    vehicleType: 'Express Bus',
    location: {
      city: 'Delhi',
      state: 'Delhi',
      lat: 28.6692,
      lng: 77.4538,
      heading: 80,
      address: 'Delhi-Meerut Expressway, Ghaziabad',
    },
    status: 'OK',
    currentSpeed: 75,
    fuelLevel: 80,
    engineTemperature: 82,
    batteryLevel: 94,
    totalDistance: 82000,
  },
  {
    vehicleId: 'BUS-002',
    registrationNumber: 'TS-07-EX-8899',
    driverName: 'Ravi Teja',
    vehicleType: 'Express Bus',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      lat: 17.2403,
      lng: 78.4294,
      heading: 190,
      address: 'Airport Approach Road, Shamshabad',
    },
    status: 'OK',
    currentSpeed: 82,
    fuelLevel: 68,
    engineTemperature: 85,
    batteryLevel: 90,
    totalDistance: 71500,
  },
  {
    vehicleId: 'SEMI-001',
    registrationNumber: 'MH-43-ST-4001',
    driverName: 'Balwant Singh',
    vehicleType: 'Semi-Trailer',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      lat: 18.9500,
      lng: 72.9500,
      heading: 260,
      address: 'JNPT Port Container Terminal, Navi Mumbai',
    },
    status: 'OK',
    currentSpeed: 50,
    fuelLevel: 74,
    engineTemperature: 84,
    batteryLevel: 92,
    totalDistance: 115000,
  },
];
